name: Save songs

on:
  schedule:
  - cron: '30 6 * * 1'
  workflow_dispatch:

jobs:
  execute-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code	
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: python main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          DISCOVER_WK_ID_0: ${{ secrets.DISCOVER_WK_ID_0 }}
          DESTINATION_ID_0: ${{ secrets.DESTINATION_ID_0 }}
          DISCOVER_WK_ID_1: ${{ secrets.DISCOVER_WK_ID_1 }}
          DESTINATION_ID_1: ${{ secrets.DESTINATION_ID_1 }}
          DISCOVER_WK_ID_2: ${{ secrets.DISCOVER_WK_ID_2 }}
          DESTINATION_ID_2: ${{ secrets.DESTINATION_ID_2 }}
          DISCOVER_WK_ID_3: ${{ secrets.DISCOVER_WK_ID_3 }}
          DESTINATION_ID_3: ${{ secrets.DESTINATION_ID_3 }}
